function AnalysisDashboard({ analysis }) {
  if (!analysis) {
    return null;
  }

  const { repository, health } = analysis;

  return (
    <section className="px-6 pb-20">
      <div className="mx-auto max-w-6xl">

        <div className="mb-8">
          <h2 className="text-3xl font-bold text-white">
            Analysis Dashboard
          </h2>

          <p className="mt-2 text-gray-400">
            Repository insights generated by RepoMirror.
          </p>
        </div>

        <div className="grid gap-6 md:grid-cols-2">

          <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6">
            <p className="text-sm text-gray-500">
              Repository
            </p>

            <h3 className="mt-2 text-2xl font-semibold text-white">
              {repository.fullName}
            </h3>

            <p className="mt-2 text-gray-400">
              {repository.description || "No description available."}
            </p>

            <div className="mt-6 flex flex-wrap gap-4 text-sm text-gray-400">
              <span>⭐ {repository.stars}</span>
              <span>🍴 {repository.forks}</span>
              <span>💻 {repository.language || "Unknown"}</span>
            </div>
          </div>

          <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6">
            <p className="text-sm text-gray-500">
              Overall Health
            </p>

            <div className="mt-4 flex items-end gap-3">
              <span className="text-6xl font-bold text-white">
                {health.score}
              </span>

              <span className="mb-2 text-gray-400">
                / 100
              </span>
            </div>

            <p className="mt-3 text-lg text-purple-400">
              {health.grade}
            </p>
          </div>

        </div>

         <div className="mt-6 grid gap-6 md:grid-cols-2">

          {/* Recommendations */}
          <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6">
            <div className="flex items-center justify-between">
              <h3 className="text-xl font-semibold text-white">
                Recommendations
              </h3>

              <span className="rounded-full bg-red-400/10 px-3 py-1 text-sm text-red-300">
                {analysis.recommendations.totalRecommendations}
              </span>
            </div>

            <div className="mt-5 space-y-4">
              {analysis.recommendations.recommendations.map(
                (recommendation, index) => (
                  <div
                    key={index}
                    className="rounded-xl border border-white/10 bg-white/[0.02] p-4"
                  >
                    <div className="flex items-center gap-3">
                      <span
                        className={`text-xs font-semibold uppercase ${
                          recommendation.severity === "High"
                            ? "text-red-400"
                            : recommendation.severity === "Medium"
                            ? "text-yellow-400"
                            : "text-blue-400"
                        }`}
                      >
                        {recommendation.severity}
                      </span>

                      <span className="text-sm text-gray-500">
                        {recommendation.category}
                      </span>
                    </div>

                    <p className="mt-2 text-sm leading-6 text-gray-300">
                      {recommendation.message}
                    </p>
                  </div>
                )
              )}
            </div>
          </div>

          {/* Strengths */}
          <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6">
            <h3 className="text-xl font-semibold text-white">
              Strengths
            </h3>

            <p className="mt-2 text-sm text-gray-500">
              Good engineering practices detected in this repository.
            </p>

            <div className="mt-5 space-y-3">
              {analysis.recommendations.strengths.map(
                (strength, index) => (
                  <div
                    key={index}
                    className="flex items-start gap-3 rounded-xl border border-white/10 bg-white/[0.02] p-4"
                  >
                    <span className="text-green-400">✓</span>

                    <p className="text-sm leading-6 text-gray-300">
                      {strength}
                    </p>
                  </div>
                )
              )}
            </div>
          </div>

        </div>

      </div>
    </section>
  );
}

export default AnalysisDashboard;